name: Frontend CI

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # @link https://github.com/actions/checkout
      - name: Frontend React
        uses: actions/checkout@v3

      - name: Create React App
        run: npx create-react-app  ci-github/

      - name: node modules
        run: cd ci-github && npm install

      - name: Build da aplicação
        run: npm run build

      - name: Testes
        run: npm test
